services:
  app:
    image: 'app:latest'
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=backend_db'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    expose:
      - 5432
