name: Deploy Backend Blog
on:
  push:
    branches: [features/gitactions]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build project
        run: mvn clean install #-DskipTests
      - name: Login DockerHub
        run: docker login -u {{secrets.DOCKER_USERNAME}} -p {{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t cesaraguc/blog-backend .
      - name: Push image docker
        run: docker push cesaraguc/blog-backend
